USE master
GO

--CRIANDO O BANDO DE DADOS

CREATE DATABASE [Fernandes]
 
GO
USE [Fernandes]
GO

-- CRIANDO A TABELA DE MIGRATIONS DO EF

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

-- CRIANDO A TABELA DE LOG DE IMPORTAÇÃO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LogImportacao](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[NomeArquivo] [varchar](255) NOT NULL,
	[DataImportacao] [datetime] NOT NULL,
 CONSTRAINT [PK_LogImport] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

-- CRIANDO A TABELA DE Alunos

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Alunos](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](50) NOT NULL,
	[PagamentoMensal] [decimal](18, 6) NOT NULL,
	[DataVencimento] [datetime] NOT NULL,
	[CriadoEm] [datetime] NOT NULL,
	[ProfessorId] [int] NOT NULL,
 CONSTRAINT [PK_Alunos] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

-- CRIANDO A TABELA DE PROFESSORES
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Professores](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](50) NOT NULL,
	[CriadoEm] [datetime] NOT NULL,
 CONSTRAINT [PK_Professores] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO




CREATE NONCLUSTERED INDEX [IX_Alunos_ProfessorId] ON [dbo].[Alunos]
(
	[ProfessorId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

-- ALTERANDO OS CAMPOS DE DATAS DA TABELA PARA SEREM AUTOMATICAMENTE SETADOS COMO DATETIME

ALTER TABLE [dbo].[LogImportacao] ADD  DEFAULT (getdate()) FOR [DataImportacao]
GO
ALTER TABLE [dbo].[Alunos] ADD  DEFAULT (getdate()) FOR [DataVencimento]
GO
ALTER TABLE [dbo].[Alunos] ADD  DEFAULT (getdate()) FOR [CriadoEm]
GO
ALTER TABLE [dbo].[Professores] ADD  DEFAULT (getdate()) FOR [CriadoEm]
GO
ALTER TABLE [dbo].[Alunos]  WITH CHECK ADD  CONSTRAINT [FK_Alunos_Professores_ProfessorId] FOREIGN KEY([ProfessorId])
REFERENCES [dbo].[Professores] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Alunos] CHECK CONSTRAINT [FK_Alunos_Professores_ProfessorId]
GO
USE [master]
GO
ALTER DATABASE [Fernandes] SET  READ_WRITE 
GO
